server:
  port: 80
spring:
  application:
    name: springCloud-consumer-80
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7001:7001/eureka,http://eureka-7002:7002/eureka,http://eureka-7003:7003/eureka
  #自定义eureka 控制台
  instance:
    instance-id: springCloud-consumer-80  #别名
    prefer-ip-address: true #显示ip
