server:
  port: 8002

spring:
  application:
    name: springCloud-dept
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7001:7001/eureka,http://eureka-7002:7002/eureka,http://eureka-7003:7003/eureka
  #自定义eureka 控制台
  instance:
    instance-id: springCloud-dept-8002   #别名
    prefer-ip-address: true #显示ip

info:
  app.name: rj-springCloud-demo
  company.name: ebiz
  build.artifactId: $project.artifactId$
  build.version: $project.version$

